<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Blogs</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>34a3eca5-2fa1-42f1-b018-e5cb2d3ec861</testSuiteGuid>
   <testCaseLink>
      <guid>16609a20-f2f4-4995-b914-30ee95bb600a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/CloseModal_AddBlogtoDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>effd9554-6bd8-4edb-a814-3d5d620c1e06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>946c50e1-953f-45e5-9f4a-dc22b0809414</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91d77610-85dd-4461-9a63-6a262e70b352</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/close Modals Blog</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>babc1301-04b4-474e-bddf-df10646c8a71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/Verify_Draft/Draft_Add_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc653a58-a2ae-4c42-a6f5-fa94c5619bf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb8c4aac-01bd-450d-9806-be5e731eacbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c7bf817-c7d6-43f7-902b-0ebb606d0371</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3cfc5f6-e9fc-4a36-92b1-2b0b95b3fc71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/Verify_Draft/Draft_Edit1_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4f9a2e0-6b32-4b6c-bfa4-00e92d8aa893</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de48ef81-d6e0-49cd-9394-14e1e8336362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1085dbb7-ed30-47b1-8236-a5a838a561c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a32b9b0b-287b-42c4-b739-ca2af3757c5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc5114f9-6358-4749-a187-a2cb0646402a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce8d0bcb-1a12-4eed-8732-47dd40f94804</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/Verify_Draft/Draft_Add_Delete_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>776f577c-6a34-477f-8adc-c9b2835b6b81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e52122a-b866-4371-bf04-0db4b346ff80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa42c8be-1e2f-40fc-91c1-1ed8885236b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa4befa3-7ffc-4eb2-aa36-3c9314b9ed20</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/Verify_Draft/Draft_Send_to_review_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>582e718b-6019-4953-a7c8-fc5c0799915d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f29b1b4-fa79-45e8-9e3f-2d4c86200a73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>846b4c14-6ccd-4db7-8a16-3c243986f4d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47d9cf8e-c997-404a-9a0b-2cfa32c2b3fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8389e284-5a12-44bc-ad16-910d4a071f97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57c8f3a0-985a-4ff5-ac4d-d805596c4f13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/Verify_Send_to_review/Send_to_review_Add_blogs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72328773-8452-47bd-9753-51913407afb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48f1bd2c-b663-4589-81e8-c827b129a56d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c2feb2c-8fd7-42f4-aa79-be2ab066d9a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad534ff3-c54e-4fb5-b480-896c4056652f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/Verify_Send_to_review/Send_to_review_Edit_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>848f33ce-3bbc-4e31-871a-4c3cc0984d37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3361db1f-2b19-423a-abb1-5054f9921993</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff8d1158-490f-4b6f-9a1c-4d79b07e8e01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79608eb2-9a78-4d15-b15d-81f7793a42d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>762d9413-2d10-4dc2-904a-88a24fa421a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e948e08-2b54-4a26-93b9-7f782f7fdda6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/Verify_Send_to_review/Send_to_review_Add_Delete_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a426f268-819d-4136-a44d-447547340274</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>162648fd-0a8c-43d0-b685-ce8fa000cf61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6529358f-366f-4309-bdd8-3c153a618a71</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
