<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Pages</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-07-18T10:48:11</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>640c12f0-6684-43fe-a069-0fa8a037b522</testSuiteGuid>
   <testCaseLink>
      <guid>7a42e904-f946-4c34-8c1c-46fb5824e5dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Via Website</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7e6d2aac-ffc2-4546-8fef-8729ea82ca97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Add</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eec73a7-2f12-40f9-a81e-5192df5a7be5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aaf1bf1-bc47-4379-a8ee-c8400cdc10a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>443ee495-311b-4fa3-9da0-f8a5289c4cea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Edit1</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db4121eb-cda3-44f7-bbbc-e9d83dcc5826</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34d3a66d-21de-44cd-be3e-06dbbee58860</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38693a0d-9f44-437a-adec-3cb5bfb10e12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5f4605c-3384-4e88-bbd7-8f57afb49209</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d475552-20d5-4d88-9e88-75ee5b6cccf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Add_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>553ed446-a7e0-46fb-a53b-83d6b4082823</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4adadfe1-125a-46e1-9667-61a0345de935</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01d09b26-6325-4e27-b619-a5e933297045</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Add</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b178555d-07d3-42c1-9806-051dbb2f3a24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b07869a4-bea3-422b-89db-aa9fa3ccd15d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41b15b31-547c-4563-b4eb-6f5dfc9c1adf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Add</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b178555d-07d3-42c1-9806-051dbb2f3a24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b07869a4-bea3-422b-89db-aa9fa3ccd15d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a71bd131-73c1-4d26-b862-fb342992cc5f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Edit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c689248-0247-4a13-944c-0c31aa384df8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e77cb2b5-f71d-44f6-b03a-ae62d60efa3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55f9d16a-e39e-4fbd-aa1d-af11c8dc3860</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9263ad-584f-4ef7-a708-cad91ee7c7d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe0ed45d-f307-4986-9f00-14d75ddb13fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Add_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8cc6b40-a7ba-4b3d-a2de-e35ea5229094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d554f30-9de9-4c22-b7b9-7cc047ee9c50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a4f89e3-711e-4834-be82-1dabcb3442ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/CloseModal_AddPagetoDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce514531-1e3c-4db1-bc94-29caf1838f35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a386514-21e6-447d-a9ac-6174fdc281e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e5f5a37-e3b1-49b1-9ae4-eef335bc2926</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/close Modals</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
