<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Page Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-06-30T14:28:59</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>2c46111e-f860-4049-8bc3-41a5764521bd</testSuiteGuid>
   <testCaseLink>
      <guid>98e8e866-e29d-4610-a1be-834cecd5d1f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Add</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eec73a7-2f12-40f9-a81e-5192df5a7be5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aaf1bf1-bc47-4379-a8ee-c8400cdc10a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>368a0dba-3efe-49ab-a334-1dee0f4614d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Edit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c689248-0247-4a13-944c-0c31aa384df8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e77cb2b5-f71d-44f6-b03a-ae62d60efa3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55f9d16a-e39e-4fbd-aa1d-af11c8dc3860</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9263ad-584f-4ef7-a708-cad91ee7c7d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6fc08ddb-dba3-4191-b478-4430d9555a65</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/close Modals</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0dc79742-54fa-4a62-8a04-021867817f33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Send_to_review</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c3f0a12-5a17-4f2b-bd94-104c69c2ba7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d428bdf8-13c9-4879-b0f6-7d649580f4e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11c2a0ce-fab1-41c1-bc36-618395081e9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25935ca7-c1af-4499-9005-5e6f18daf855</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
