<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Pages</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-07-18T10:48:11</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>640c12f0-6684-43fe-a069-0fa8a037b522</testSuiteGuid>
   <testCaseLink>
      <guid>7a42e904-f946-4c34-8c1c-46fb5824e5dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Via Website</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ffa89138-2e21-40e2-8b09-a95e09b5f8dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Add</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3eec73a7-2f12-40f9-a81e-5192df5a7be5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aaf1bf1-bc47-4379-a8ee-c8400cdc10a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ee56951-7c96-4d52-a7a9-95627fc06844</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/close Modals_AddButton</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>45765441-92c0-4453-a099-33e31f58a6d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/CloseModal_AddPagetoDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce514531-1e3c-4db1-bc94-29caf1838f35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a386514-21e6-447d-a9ac-6174fdc281e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6846c10-d089-4a29-9b0a-21f63f42874c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Edit1</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>058412c2-f020-4756-b7b9-85154bea0d5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Add_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>553ed446-a7e0-46fb-a53b-83d6b4082823</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4adadfe1-125a-46e1-9667-61a0345de935</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0b03068-c59a-4efc-8d5d-b038a6facc40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Draft/Draft_Send_to_review</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c3f0a12-5a17-4f2b-bd94-104c69c2ba7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d428bdf8-13c9-4879-b0f6-7d649580f4e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11c2a0ce-fab1-41c1-bc36-618395081e9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25935ca7-c1af-4499-9005-5e6f18daf855</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04d21b9f-19da-41c9-8fef-0c445e592684</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Add</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b178555d-07d3-42c1-9806-051dbb2f3a24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b07869a4-bea3-422b-89db-aa9fa3ccd15d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>382aeb68-f32d-4240-a3cc-fc12839f7470</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Edit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c689248-0247-4a13-944c-0c31aa384df8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e77cb2b5-f71d-44f6-b03a-ae62d60efa3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55f9d16a-e39e-4fbd-aa1d-af11c8dc3860</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac9263ad-584f-4ef7-a708-cad91ee7c7d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d558f32a-ed73-4e21-90a0-b2807d782dea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_Add_Delete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8cc6b40-a7ba-4b3d-a2de-e35ea5229094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d554f30-9de9-4c22-b7b9-7cc047ee9c50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>35c7ca84-ae3c-4d62-9a25-d8f27b76322d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Pages/Modal/Verify_Send_to_review/Send_to_review_edit_draft</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25da79bb-0f2a-4f56-b3b8-3803ce1e74bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>064983d9-eff5-4306-91b6-466c24794d2f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
