<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PandS_Incomplete_Items_last</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8eda82a5-1b6f-424b-b90b-c2509ba0ec36</testSuiteGuid>
   <testCaseLink>
      <guid>fcf23090-e9ee-41a3-842c-c5549e6e6b40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/close_PandS_Modals</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d8e0c2ba-c45f-497e-9783-80610ae2f4d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/CloseModal_Add_PandS_toDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e753e907-1fad-46e7-8868-3fc1fb2dbd51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77d659c7-3fbf-4eee-b27e-23e6395d35bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ff4c21e-52ab-495e-8048-a1c692e2c980</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Add_Delete_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f39e8ec-a4f1-4f07-bd52-7ca40b5fb0ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>967d0f9f-2b9e-4424-ac0c-c19e03602ed9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16dcc5fa-fc2e-40ee-82eb-8e51d227a427</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Add_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>573a4b75-7e3c-4015-a387-8f463567dbef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d91fb7f3-011d-47d3-8fbd-838d6c1ea5d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39f7dfc0-ee0d-45d8-9f14-66da91613a32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Edit1_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db76c10b-52b8-4a3c-b13f-05ed997f0a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93108c8b-4ce4-4861-b551-57d1c1607a0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e0b7080-eca9-4ff2-84a0-bd1dc47e35a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>497741f0-9f31-4fb9-a3f8-2de4facd9c74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e2e8e66-7a83-4f09-8dc0-8cee2ebcbe76</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Send_to_review_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>838b1d57-434f-4beb-aa54-21e763760483</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12e5ad9-b090-416b-a537-2d81cd6758e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0553021-18af-4882-9bcf-961c2812c91c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bd01f16-447e-416d-8de9-fc03bec45b2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2aa86ad8-2240-4cfb-b059-1d58049c475f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Send_to_review/Send_to_review_Add_Delete_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d773d1a3-60fb-406f-b3bd-5d91e5eaffc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa4719f7-8ea5-486c-af13-3d4433feea78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>807e6f4a-cecc-4254-9f6b-5479f6a7c8db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Send_to_review/Send_to_review_Add_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67bb8533-2288-4bb4-8b29-55df270a8507</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0f6e2b-6cb3-484e-b6e0-2f4c29f10f1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c97e1c8b-4932-402b-90cb-7e0490ba329a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Send_to_review/Send_to_review_Edit_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4319a75b-18d8-4deb-a4f6-9ae25c7263db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad60f67-0bfa-4708-8fbe-ef285c1ae25e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdc78744-6f86-439e-b203-42409cbf0f51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5616d5c0-e97e-46bd-8565-fd1b0b01456a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
