<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>PandS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-07-24T16:02:22</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8eda82a5-1b6f-424b-b90b-c2509ba0ec36</testSuiteGuid>
   <testCaseLink>
      <guid>b1017cce-b667-4b87-89dc-cb80bf372c5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Via Website</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d3df9982-edf0-4497-bc6b-97abeee40d80</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/AddWeightDefaultContent</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0e53be6c-9c1d-4762-8e76-70ee519d2d18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Add_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>573a4b75-7e3c-4015-a387-8f463567dbef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d91fb7f3-011d-47d3-8fbd-838d6c1ea5d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5aa78ae3-44ee-483d-97a8-2f92c979429e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/CloseModal_Add_PandS_toDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e753e907-1fad-46e7-8868-3fc1fb2dbd51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77d659c7-3fbf-4eee-b27e-23e6395d35bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d5d65b0-ef48-41a3-a11f-593af68b9acf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/close_PandS_Modals</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>918c2b5c-db07-4148-89c9-5816afd82c9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Edit1_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db76c10b-52b8-4a3c-b13f-05ed997f0a6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93108c8b-4ce4-4861-b551-57d1c1607a0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e0b7080-eca9-4ff2-84a0-bd1dc47e35a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>497741f0-9f31-4fb9-a3f8-2de4facd9c74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>660e5db2-b72d-42e2-9496-326c54cfb1b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Add_Delete_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f39e8ec-a4f1-4f07-bd52-7ca40b5fb0ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>967d0f9f-2b9e-4424-ac0c-c19e03602ed9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>787f203e-4bd4-4c6e-bd6d-8d17a600cf6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Draft/Draft_Send_to_review_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>838b1d57-434f-4beb-aa54-21e763760483</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c12e5ad9-b090-416b-a537-2d81cd6758e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0553021-18af-4882-9bcf-961c2812c91c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bd01f16-447e-416d-8de9-fc03bec45b2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>885ac832-4337-462f-baba-49810a3fe1ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Send_to_review/Send_to_review_Add_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67bb8533-2288-4bb4-8b29-55df270a8507</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0f6e2b-6cb3-484e-b6e0-2f4c29f10f1b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7828e3ef-5407-4413-980b-18098d80c36b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Send_to_review/Send_to_review_Edit_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4319a75b-18d8-4deb-a4f6-9ae25c7263db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad60f67-0bfa-4708-8fbe-ef285c1ae25e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdc78744-6f86-439e-b203-42409cbf0f51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5616d5c0-e97e-46bd-8565-fd1b0b01456a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7fac4f19-1a1b-41e8-aacc-b4880ebb0373</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Send_to_review/Send_to_review_Add_Delete_PandS_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d773d1a3-60fb-406f-b3bd-5d91e5eaffc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa4719f7-8ea5-486c-af13-3d4433feea78</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54f54445-c56d-4e4c-9325-88cc188b41d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Product and Services/Modal/Verify_Send_to_review/Send_to_review_Edit_PandS_Draft</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d77de5f-61d0-4eb6-85e7-2eae959d7738</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2405abb3-f131-468f-b488-e2fc08d28026</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd2d735e-e172-4eb2-b909-3ef3b1273165</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f8b5c27-cd90-43fd-849e-a3cb1bdd614c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
