<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Team Members</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-07-18T10:48:11</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b41144d9-da5e-4a53-841e-b3b1a0b82295</testSuiteGuid>
   <testCaseLink>
      <guid>9be1066d-31ac-48d8-806d-3a847e85d5f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Via Website</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6c742922-8d66-48e1-8ec3-abcb422b4c33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/close_Team_Modals</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a29b3c84-a242-45db-bf1f-996ce8b29741</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/Verify_Draft/Draft_Add_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86a7ba00-7f3c-4755-834e-d6666c80a1ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a7ed524-3ff3-4fd8-8433-f904b7be32a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b8a6ce2-8994-4035-92be-7991b7ad5376</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf0eef95-7c7a-4038-8b07-610b81782332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e87e170-6d00-4654-a691-5421a084f7f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e2f328c-5b23-4629-bcd4-99ac429d7f9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf92791c-604c-4834-9929-124bb875d5e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f48ea579-0e72-46e4-a5e3-725ef1a8e59c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7839bf4-98ca-43d5-beeb-e877efec33b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e38e23fc-f5fb-41d8-a373-7710c7c31ce2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9ef31a8d-438a-4857-8c0a-0686907bf173</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/Verify_Draft/Draft_Edit_Team</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2e2eca8-4c6f-4e8a-836b-9ffef9f138a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>266c5121-7203-43a0-bd71-2779bcec4dc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56b1b4c4-3e15-452a-93d8-76a2ea7966ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a931d9e5-b8fe-464a-9a76-b1e4f67bed9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48c2fa1d-08db-43f7-88a6-d9b628ecd1ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>368ddfc9-1f90-4d08-9dca-abc2f15cb0ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab08d8cb-acf1-40a4-bf6d-97a483fd0ce4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7de5c670-d2e5-4b4a-8ae2-dea1385c5225</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>432a4fe2-0ecd-4592-8c23-9cc8666dbfbd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e3b3ce-049b-4602-94d4-2b6faa272e49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e267cb45-d259-4bfb-ad92-5ccc5b33239a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/Verify_Draft/Draft_Send_to_review_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>868b79ae-850e-499f-9035-191768e95276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6cfd645-1cc9-4073-a6df-8127a8b0c1e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65ee582e-17ae-450b-a7ec-3f3f48375d23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c8753e-b02c-4926-8d7a-b0414f722532</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>505c4c59-a25e-44f2-b441-760bbb97a273</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/CloseModal_Add_Team_toDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5d45a7d-9ffa-4c22-9e67-b326d15e0ba3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99b3b6b3-f47c-4fbd-a296-3ce8053534a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ec1bf86-53b4-4809-9de6-0a8bca165141</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/Verify_Draft/Draft_Add_Delete_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52c276e9-3871-4eaa-baa9-9637b77cc629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ddecbfd-2883-484d-8491-3c27af60adaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b7877c1-541c-404f-9e89-4ede4831c272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c87fe800-6cd9-405e-8d83-b44f60c7455c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca07fbd1-ece4-4d76-b7bc-3ca030169cfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01144ada-029e-41e3-a5cc-4f54f9dbac4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95efd90c-0509-494d-a1da-5c13aba48146</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c395702-3c0a-41dc-8f85-17836b68663f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb3dbd0e-0082-4325-96bd-d51041fb82d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e213186-780c-48de-a2cd-fb4c1c9e7aae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d49285d-1f6f-471d-916e-b0326165f69b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/Verify_Send_to_review/Send_to_review_Add_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>047c352a-f41c-4d94-b58e-e0a7c98cf057</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c72f6513-b55d-4a14-8e42-7f8d89cb95bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcfb50b0-2f56-4ab6-bb1e-b5d8484774d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15d22ff7-5ffe-4911-8abf-721a5f43002c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7a48d90-9fcf-47df-8303-cd4378beba36</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6742ebdb-b02c-4b94-a3a2-4d16eafaa8df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4783b566-715f-4e42-92ff-6619012a3baf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99603e1b-43ba-4dcb-a18b-1ebfe1c83b94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc4affb-968f-433d-ac86-23c5152a9e17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cae648f-42f2-4980-80ec-b126598b8e1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41126bf5-dbce-4883-9762-17d0ed5c44f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/Verify_Send_to_review/Send_to_review_Edit_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bd54908-064a-49ef-aded-f6d6eb7a3fa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a2a7c68-6c47-4ab5-b908-35412b8471ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee390bbb-d4bb-4508-a8c8-d65312dc88d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d458c35e-c32c-4a0f-b969-a319189abd5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7480b11b-2e4f-4745-b667-c3fdb04fe59f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cebac328-7616-4159-8ecf-af3b64252559</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844cd6ad-f35d-4335-8fbf-9be53956fbd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0bdc1e5-93d6-4a8c-bc85-69651f12e5b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f456b171-73f2-4760-aa25-bdf82e1402f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28bdefbe-942e-4285-ba99-25f597ee69bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d9df1cf-52ca-4cd2-8640-fadbd0b2e755</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/Verify_Send_to_review/Send_to_review_Add_Delete_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef7ce5ea-f68b-42c0-9f8b-c37b64df1f70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0773e99b-dba1-43ab-b323-a754032eef33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29042a4b-6abd-478d-b565-c403eef942e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e426915-7150-42d0-a47c-a40a17e61d06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d42ff888-87e1-4cd8-8ba7-084f6c310d9a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfbaee6a-4cc4-447c-9d2d-099e7917b067</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95b0e889-72a7-44ee-834a-72238c57f9cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7fa5634c-df19-4355-80a0-63b835fca9de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5afc7f9d-3278-4c19-8182-d8cb8b76ef1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05fbc521-a0d8-40a0-a49a-507b06f0dac3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
