<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_close</name>
   <tag></tag>
   <elementGuidId>636c5af9-33be-499f-b377-1241d2453eae</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;touchevents details js wf-lato-n4-active wf-active&quot;]/body[@class=&quot;layout-no-sidebars path-user off-canvas-wrap&quot;]/div[@class=&quot;inner-wrap&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;region region-messages&quot;]/div[1]/ul[@class=&quot;messages__list&quot;]/li[@class=&quot;alert-box status messages__item&quot;]/a[@class=&quot;close&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
   </webElementProperties>
</WebElementEntity>
