<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Blogs</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-09-12T14:01:35</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>34a3eca5-2fa1-42f1-b018-e5cb2d3ec861</testSuiteGuid>
   <testCaseLink>
      <guid>9b635b82-97c7-418a-b271-1d7a6978c0a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Via Website</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>645fc601-5147-409e-8a3f-22d26f479a4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Draft/Draft_Add_blog</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3d713ba6-849f-42a6-a2de-08d5af70b9bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/close Modals Blog</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>decef0f7-51d1-49a1-a237-8eced13374b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/CloseModal_AddBlogtoDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>effd9554-6bd8-4edb-a814-3d5d620c1e06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>946c50e1-953f-45e5-9f4a-dc22b0809414</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6906158-d1cb-4ac1-870c-cd504b2e2b04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Draft/Draft_Edit1_blog</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a3634b32-7e76-4b04-9741-a5b7e4c5a76d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Draft/Draft_Add_Delete_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>776f577c-6a34-477f-8adc-c9b2835b6b81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e52122a-b866-4371-bf04-0db4b346ff80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa42c8be-1e2f-40fc-91c1-1ed8885236b7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e764cd5-c297-425f-abbf-a3120d559ae0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Draft/Draft_Send_to_review_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>582e718b-6019-4953-a7c8-fc5c0799915d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f29b1b4-fa79-45e8-9e3f-2d4c86200a73</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>846b4c14-6ccd-4db7-8a16-3c243986f4d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47d9cf8e-c997-404a-9a0b-2cfa32c2b3fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8389e284-5a12-44bc-ad16-910d4a071f97</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45c2a7df-7be6-45ad-abd6-9bda26ca0d33</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Send_to_review/Send_to_review_Add_blogs</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72328773-8452-47bd-9753-51913407afb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48f1bd2c-b663-4589-81e8-c827b129a56d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c2feb2c-8fd7-42f4-aa79-be2ab066d9a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb69cad7-d821-4d91-ac82-d25130b95fb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Send_to_review/Send_to_review_Edit_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>848f33ce-3bbc-4e31-871a-4c3cc0984d37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3361db1f-2b19-423a-abb1-5054f9921993</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff8d1158-490f-4b6f-9a1c-4d79b07e8e01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79608eb2-9a78-4d15-b15d-81f7793a42d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>762d9413-2d10-4dc2-904a-88a24fa421a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff9b51fb-f903-493c-8bd6-88abcb4dad37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Send_to_review/Send_to_review_Add_Delete_blog</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a426f268-819d-4136-a44d-447547340274</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>162648fd-0a8c-43d0-b685-ce8fa000cf61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6529358f-366f-4309-bdd8-3c153a618a71</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83e3d271-1b4d-43c3-9db6-31c81c8e3b8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Blogs/Modal/No Images/Verify_Send_to_review/Send_to_review_Edit_blog_Draft</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>787eeb00-6203-4a04-aadd-59b074169a24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>193a9d06-5295-45fe-ab5b-644f239b8eb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>884ad594-3ba8-494a-8e07-50bc832cfa0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e7c4e2-5522-4507-b06a-8622695953e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4defe91-b1f7-4d0e-aeb0-58b22b00febc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
