<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Events</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e073b70e-87af-48e9-a598-d96672d52433</testSuiteGuid>
   <testCaseLink>
      <guid>0ce66da2-8bac-4bf7-8ec1-409c25cb2df0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Via Website</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7a563b3d-bd2f-486e-aaf7-aa003c13db03</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Draft/Add a Draft Event</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1ac3a9f4-29bd-4d37-9f2e-09afa3440345</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/close_Events_Modals</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fa33b5a8-9816-457a-9b76-2aff0efc2f87</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/Close Modal to Delete Events</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>872a368d-e461-49f4-a927-4730461e1527</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7df7e2-8b2d-478b-9caa-ccbb01165f0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f22d19c3-83d4-42d9-9bde-2aec0356bd37</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Draft/Edit a Draft Event</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1e5c8bd0-e521-445a-926a-18e22cd0d587</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Draft/Delete a Draft Event</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1e506ac-a385-4f52-b7ea-06a55b322959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d7136e8-4bde-4d44-8069-7f498f8ad880</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>534af665-de4e-4bc8-a420-ea8b9fa3ed78</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f58b3eb7-7eaa-415a-9f37-e4681d860bfc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>644b8740-b6fc-4079-aee3-72a5e1472838</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01a1f9ba-eb73-4668-b6d4-a5ce4c48b9c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05c2d30e-3bec-4c24-96ff-a6f5a8d69b33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ce3b484-95c7-4e6a-9032-a7736322621a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aebafaae-6969-461e-b4b6-f191a4cd7aed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8dc99d43-2f84-44b8-b14b-1d050d035da3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56611b82-9fff-4149-a745-f040855b1301</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Draft/Send a Event to review</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eaaf2b7-d469-47e7-8e10-158c2fe488a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fde677da-a538-4a5b-a5e1-7308c053f51f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9e77f89-934b-43ab-bc3f-980cc807b919</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbe8dd8b-54d6-492b-8f14-8cb5dd0eff42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed090f53-05f9-4279-a114-f743af73192a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Send_to_review/Send_to_review_Add_Event_</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5159d23d-9161-4d1c-b2f2-e0e1b65a4af7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Send_to_review/Send_to_review_Edit_Event</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2600accf-2d83-45a1-ab9a-93f88516e689</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b8ddd03-53c2-4ead-a6e9-df0feb1a27c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4617a3f6-02b5-4f32-9b07-3e392c4d53dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecdec74f-f874-45a7-a377-7b8489446893</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f6cea4b-39dc-4d3d-9858-aaa4e0f87df2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>374df559-db49-4e64-a96f-92b07673fa3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a6c4520-22c0-457b-af95-0a3f6d7ab5c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef2cf71c-a85c-4f90-9315-8953c22df457</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31ae52d6-fd8c-42ea-a640-9d77d5e9e3e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1531c7b-5b6b-4f4c-ad44-bcf57131feba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2565bf5f-396d-42e7-96b0-ee2143876959</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Send_to_review/Send_to_review_Add_Delete_Event_</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8e3caea4-acc8-4e1d-b9c2-25da8f83d13c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Events_Buggy/Modal/No Images/Verify_Send_to_review/Send_to_review_Edit_Event_draft</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67ab2d6d-b834-4c13-be1b-7d6dd7e23106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c94d947-eaee-44a1-8ed9-614761e59c87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de6b4d0d-c74d-4b3f-bd65-e19ce2028a19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f997b81a-5bcb-45a6-8c27-30748694fff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1b927f7-346e-40ba-93e0-b8829fad6924</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbe162da-0440-4297-954d-16f68b119d13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cd967a9-2fbe-48cf-857d-1fcbc39a4255</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b0293d2-e3b2-4b06-9b47-07ad29ed70c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c0054d-a846-4707-90b0-eb07591c5751</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41860210-da52-4f54-9839-81fadb40fbf2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
