<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Team Members</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2017-09-14T12:20:40</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <testSuiteGuid>b41144d9-da5e-4a53-841e-b3b1a0b82295</testSuiteGuid>
   <testCaseLink>
      <guid>9be1066d-31ac-48d8-806d-3a847e85d5f7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login Via Website</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c48061e3-91b6-4f8b-8b72-572dcf8a8a8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Draft/Draft_Add_Team_</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a182208f-58f6-4a69-ba9d-2cdd6810753b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/CloseModal_Add_Team_toDelete</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5d45a7d-9ffa-4c22-9e67-b326d15e0ba3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99b3b6b3-f47c-4fbd-a296-3ce8053534a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1804fac-6862-4856-a62b-c4f5478dc30a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/close_Team_Modals</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d5db7071-3a55-4158-9268-bc8897b9bd42</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Draft/Draft_Edit_Team</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>62836f1b-f399-4fa1-aa27-46fcb24688e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Draft/Draft_Add_Delete_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52c276e9-3871-4eaa-baa9-9637b77cc629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ddecbfd-2883-484d-8491-3c27af60adaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b7877c1-541c-404f-9e89-4ede4831c272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c87fe800-6cd9-405e-8d83-b44f60c7455c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca07fbd1-ece4-4d76-b7bc-3ca030169cfe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01144ada-029e-41e3-a5cc-4f54f9dbac4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95efd90c-0509-494d-a1da-5c13aba48146</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c395702-3c0a-41dc-8f85-17836b68663f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb3dbd0e-0082-4325-96bd-d51041fb82d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e213186-780c-48de-a2cd-fb4c1c9e7aae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0f7d153-3ed8-4c88-a849-a0c850b30c62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Draft/Draft_Send_to_review_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>868b79ae-850e-499f-9035-191768e95276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6cfd645-1cc9-4073-a6df-8127a8b0c1e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65ee582e-17ae-450b-a7ec-3f3f48375d23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38c8753e-b02c-4926-8d7a-b0414f722532</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3bcea9dd-6b65-4b00-8758-0ce538a257f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Send_to_review/Send_to_review_Add_Team_</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7f244f7f-db2e-447e-b21d-82d18c94581e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Send_to_review/Send_to_review_Edit_Team_</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bd54908-064a-49ef-aded-f6d6eb7a3fa9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a2a7c68-6c47-4ab5-b908-35412b8471ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee390bbb-d4bb-4508-a8c8-d65312dc88d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d458c35e-c32c-4a0f-b969-a319189abd5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7480b11b-2e4f-4745-b667-c3fdb04fe59f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cebac328-7616-4159-8ecf-af3b64252559</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844cd6ad-f35d-4335-8fbf-9be53956fbd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0bdc1e5-93d6-4a8c-bc85-69651f12e5b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f456b171-73f2-4760-aa25-bdf82e1402f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28bdefbe-942e-4285-ba99-25f597ee69bc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1770c43f-3366-4630-a5d2-0d9b28d9458b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Send_to_review/Send_to_review_Add_Delete_Team_</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d6a55eab-3caa-4282-95c9-9ecd1f8f2c74</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/My Content/Our Team/Modal/No Images/Verify_Send_to_review/Send_to_review_Edit_Team_draft</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07c57f93-ea0f-423a-8f7a-da480f43372c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aaedde7-dfb6-46b3-b175-5cfad326a78e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7562f31-e34a-42cc-a12f-a07d0c76b177</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2a5b0d8-4391-4d9a-9a17-c8be77e84f04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25f2cb2a-f351-414d-aae9-6344756badc7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd9bf57-70b3-42aa-9dd4-221fd8610996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>213f8cdb-fa6e-4a24-8706-39475b9aae93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaeb1bc3-94e4-4bf2-833a-6027871722d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8066fbdb-37bc-44c5-9c6f-a78fd4670190</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>245284da-1975-4193-96dc-7acda92fda7a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
