<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Delete</name>
   <tag></tag>
   <elementGuidId>0d6443bf-f2e6-446a-9555-dbc9af617570</elementGuidId>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-aw-dashboard-content&quot;)/div[@class=&quot;views-element-container&quot;]/div[@class=&quot;pages dashboard-content view view-pages view-id-pages view-display-id-dashboard_page js-view-dom-id-37533626dc353c61b244cb5a0c5583744ddbc8ec78db02845fbfe5c58d38f417&quot;]/div[@class=&quot;view-content&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;views-table views-view-table cols-5 table&quot;]/tbody[1]/tr[1]/td[@class=&quot;views-field views-field-entity-operations-icons&quot;]/ul[@class=&quot;operations--icons&quot;]/li[@class=&quot;delete&quot;]/a[@class=&quot;use-ajax&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hreflang</name>
      <type>Main</type>
      <value>en</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dialog-options</name>
      <type>Main</type>
      <value>{&quot;width&quot;:&quot;900px&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dialog-type</name>
      <type>Main</type>
      <value>dialog</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/node/1042/delete?destination=/dashboard/content%3Fq%3Ddashboard/content</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>use-ajax</value>
   </webElementProperties>
</WebElementEntity>
